#!/usr/bin/env bash
# Installs and configures Nginx to serve 'Holberton School' at the root page

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

service nginx restart