#!/usr/bin/env bash
# Configures Nginx with a 301 redirection for /redirect_me

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

# Insert redirection rule into default site configuration
sed -i '/server_name _;/a \    rewrite ^/redirect_me/?$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart